add_rules("mode.debug", "mode.release")

add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode", lsp = "clangd"})
target("tcpclient")
    set_kind("binary")
    add_files("src/tcpclient.c")
target("tcpserver")
    set_kind("binary")
    add_files("src/tcpserver.c")
target("thread_server")
    set_kind("binary")
    add_files("src/thread_server.c")
    add_files("src/lib/_queue.c")
target("select_server")
    set_kind("binary")
    add_files("src/selectserver.c")
target("download")
    set_kind("binary")
    add_files("src/download.c")
    add_links("curl")


